### ISSUE TITLE
net/http: Header parsing requires a single space between the header name and the value

### ISSUE THREAD

**Issue by sompylasar** [C5T/Current#100]
The [spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) says:

> The field value MAY be preceded by any amount of LWS, though a single SP is preferred. Header fields can be extended over multiple lines by preceding each extra line with at least one SP or HT.
> 
> ```
>        message-header = field-name ":" [ field-value ]
>        field-name     = token
>        field-value    = *( field-content | LWS )
>        field-content  = <the OCTETs making up the field-value
>                         and consisting of either *TEXT or combinations
>                         of token, separators, and quoted-string>
> ```
> 
> The field-content does not include any leading or trailing LWS: linear white space occurring before the first non-whitespace character of the field-value or after the last non-whitespace character of the field-value. Such leading or trailing LWS MAY be removed without changing the semantics of the field value.

Currently, the space between ":" and the value is mandatory:
https://github.com/KnowSheet/Bricks/blob/master/net/http/impl/server.h#L54

``` cpp
const char kHeaderKeyValueSeparator[] = ": ";
```

**Comment by dkorolev** [comment]
Roger, thanks.

**Comment by dkorolev** [comment]
Damn, still no time to get to this one.

Looks like a four-line fix though, on my plate.

**Comment by grixa** [comment]
Perhaps, we can close this issue after #731 ?

**Comment by dkorolev** [comment]
:+1:
