### ISSUE TITLE
net/api: Expose the response headers to the user-land code

### ISSUE THREAD

**Issue by sompylasar** [C5T/Current#103]
https://github.com/KnowSheet/Bricks/blob/master/net/http/impl/server.h#L84
`HTTPDefaultHelper` exposes `headers` but they are not exposed in the top-level API.
We should think of some way to expose the response headers in the return value of `HTTP(GET("..."))`.

**Comment by dkorolev** [comment]
Yay, `response.headers` are in since a while ago.
