### ISSUE TITLE
Need to fix image-generating tests on Linux+Mac for plotutils+gnuplot.

### ISSUE THREAD

**Issue by dkorolev** [C5T/Current#107]
http://www.quora.com/Is-there-a-platform-agnostic-and-date-time-agnostic-output-terminal-canvas-type-for-gnuplot-plotutils

(Although we might well phase out plotutils I think.)

**Comment by dkorolev** [comment]
https://twitter.com/UniqueDima/status/572633236553265152

**Comment by dkorolev** [comment]
https://www.facebook.com/dima.korolev.16/posts/856607601065221

Fingers crossed!

**Comment by sompylasar** [comment]
What about just grepping the parts that contain time? It should not be complex with SVG which I think is the preferred format for diff.

**Comment by dkorolev** [comment]
I already am thinking about it; even in the other direction: what about just grepping the lines that are the actual visual elements.

Not today though.

**Comment by dkorolev** [comment]
This has been fixed a while ago by changing the unit tests to compare the data that's input to `gnuplot`, not the result of its output. Unit tests + CI FTW!
