### ISSUE TITLE
Fix KnowSheet/scripts/Makefile for Mac

### ISSUE THREAD

**Issue by mzhurovich** [C5T/Current#109]
`readlink` returns nothing if Makefile is NOT a symlink
https://github.com/KnowSheet/Bricks/blob/master/KnowSheet/scripts/Makefile#L12

CC: @sompylasar

**Comment by sompylasar** [comment]
Too bad. Some logic should be added for this case.

**Comment by dkorolev** [comment]
God news: I could reproduce the issue and understand it.
Bad news: I can't fix it right away.
Good new: It does not affect Bricks, only projects that `include` Bricks' Makefile.

I suggest we keep this issue open, but merge https://github.com/KnowSheet/Bricks/issues/108.

**Comment by sompylasar** [comment]
@dkorolev OK.

**Comment by dkorolev** [comment]
@mzhurovich overdelivered on this one a few months ago.
