### ISSUE TITLE
Our HTTP server probably should reply with 411 Length Required for POST requests without Content-Length

### ISSUE THREAD

**Issue by biodranik** [C5T/Current#11]
It can make easier for us to test platform-dependent implementations

**Comment by dkorolev** [comment]
Isn't a POST request without Content-length just a POST request without HTTP body? CC @sompylasar

**Comment by sompylasar** [comment]
Here's what [the spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4) says:
> For compatibility with HTTP/1.0 applications, HTTP/1.1 requests containing a message-body MUST include a valid Content-Length header field unless the server is known to be HTTP/1.1 compliant. If a request contains a message-body and a Content-Length is not given, the server SHOULD respond with 400 (bad request) if it cannot determine the length of the message, or with 411 (length required) if it wishes to insist on receiving a valid Content-Length.

The server may wish to insist on a valid `Content-Length` unless it can determine the transfer-length from the request, but this is not required if the server actually can determine the length without extra hints. Anyways, the `Content-Length` header could be set to an invalid value by a malicious requestor, so it should not be relied upon.

**Comment by dkorolev** [comment]
This matches my understanding. In a simplified version it would read: If the client is sending body, it should either set `Content-length` or use chunked transfer encoding.

It is an important point, but it sounds orthogonal to what this issue is about: Does every `POST` request have to have the body?

A more general question is: Does every other, say, `GET`, request have to have `Content-length: 0` set?

**Comment by dkorolev** [comment]
#fixready https://github.com/C5T/Current/pull/800

**Comment by biodranik** [comment]
The HyperText Transfer Protocol (HTTP) 411 Length Required client error response code indicates that the server refuses to accept the request without a defined Content-Length header.

Note: by specification, when sending data in a series of chunks, the Content-Length header is omitted and at the beginning of each chunk you need to add the length of the current chunk in hexadecimal format. See Transfer-Encoding for more details.

**Comment by dkorolev** [comment]
> The HyperText Transfer Protocol (HTTP) 411 Length Required client error response code indicates that the server refuses to accept the request without a defined Content-Length header.
>
> Note: by specification, when sending data in a series of chunks, the Content-Length header is omitted and at the beginning of each chunk you need to add the length of the current chunk in hexadecimal format. See Transfer-Encoding for more details.

Щито? :-)

**Comment by biodranik** [comment]
If it's PUT/POST/PATCH and Transfer-Encoding contains "chunked", then Content-Length is omitted.

**Comment by dkorolev** [comment]
Which is exactly the present behavior, and, I believe, there's even a test for it :)

**Comment by dkorolev** [comment]
Which is exactly the present behavior, and, I believe, there's even a test for it :)

**Comment by dkorolev** [comment]
OK to close, @biodranik?

**Comment by biodranik** [comment]
Ok
