### ISSUE TITLE
Revisit Bricks exceptions.

### ISSUE THREAD

**Issue by dkorolev** [C5T/Current#116]
Now it's a good time. Agenda:

* Naming. (probably get rid of `Exception` to make those consistent.)
* Error messages. (many are missing messages now, and for most of them it's a simple fix.)
* Consistency. (we've diverted exception on Linux and MacOS, I believe. This has to be looked into.)

Thanks,
Dima

**Comment by sompylasar** [comment]
> Naming. (probably get rid of Exception to make those consistent.)

I'd stay with `Exception` and add it to every exception. Otherwise there is a chance to have a clash.

**Comment by dkorolev** [comment]
Even if they are all in a `bricks::exceptions` namespace?

**Comment by sompylasar** [comment]
Sure. You wil be `using` this namespace all the time, along with other namespaces. Looking from the API perspective, I'd like to know what kind of object I am dealing with, without looking at its namespace.

**Comment by dkorolev** [comment]
Convinced :)

**Comment by sompylasar** [comment]
P.S. Not all exceptions: `bricks::net::NetworkException` just found in Sherlock.

**Comment by dkorolev** [comment]
I'm meaning to move them.

**Comment by dkorolev** [comment]
I'm assuming this has been done with our move to `CURRENT_THROW` that also tracks `__FILE__` and `__LINE__`.
