### ISSUE TITLE
Support HTTP requests with multiple header fields having the same name

### ISSUE THREAD

**Issue by mzhurovich** [C5T/Current#147]
It's essential for tracking cookies.
More information: https://tools.ietf.org/html/rfc7230#section-3.2

**Comment by dkorolev** [comment]
Ref.: https://github.com/KnowSheet/SimpleServer/issues/3

**Comment by sompylasar** [comment]
It's essential for sending cookies from the server to the client (`Set-Cookie`). The clients (browsers) usually send all the cookies in a single `Cookie` header.

**Comment by dkorolev** [comment]
Proudly announcing this as done a while ago: IIRC, Max read the RFCs, confirmed `Cookies` are the only special case, and we made sure it's handled appropriately.
