### ISSUE TITLE
Make RTTIDispatchCall support rvalue references.

### ISSUE THREAD

**Issue by dkorolev** [C5T/Current#169]
CC @mzhurovich

**Comment by dkorolev** [comment]
Marking as possibly valid as part of the cleanup.

First of all, we have `Bricks/template/rtti_dynamic_call.h` with `RTTIDispatcher`, and it seems like `RuntimeDispatcher` from Bricks/rtti/dispatcher.h` is needed at all.

**Comment by mzhurovich** [comment]
Implemented in #661
