### ISSUE TITLE
Fix the Current repo description

### ISSUE THREAD

**Issue by sompylasar** [c5t/Current#181]
Now it resembles the Bricks' one.

**Comment by sompylasar** [comment]
CC @dkorolev

p.s. I cannot assign issues.

**Comment by dkorolev** [comment]
Yeah, it's on our todo list to edit description.

Can you not assign issues even by typing in a full GitHub account name? You
should have full access! :-/

On Sunday, May 24, 2015, John Babak <notifications@github.com> wrote:

> CC @dkorolev <https://github.com/dkorolev>
>
> p.s. I cannot assign issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/c5t/Current/issues/181#issuecomment-105137663>.
>


-- 
And, as always, have a nice day!
Dima

http://dimakorolev.com/ | http://www.linkedin.com/in/dimakorolev |
dmitry.korolev@gmail.com | +1 (312) 593 2783

**Comment by sompylasar** [comment]
@dkorolev The issue properties on the right (Labels, Milestone, Assignee) do not appear editable for me as they should.

**Comment by mzhurovich** [comment]
Looks like it was fixed.
