### ISSUE TITLE
net/http: Default impl does not store multiple headers with the same name

### ISSUE THREAD

**Issue by sompylasar** [C5T/Current#98]
For example, [some](http://caolanmcmahon.com/posts/multiple_set_cookie_headers_in_node_js/) [servers](https://github.com/strongloop/express/commit/08497683bf7421210efce8a7361b869c1eac76ae) may respond with multiple `Set-Cookie` headers (this is done for browser compatibility). The following code only allows one header per name:
https://github.com/KnowSheet/Bricks/blob/master/net/http/impl/server.h#L84
```cpp
typedef std::map<std::string, std::string> HeadersType;
// ...
inline void OnHeader(const char* key, const char* value) { headers_[key] = value; }
// ...
HeadersType headers_;
```

The `std::map<std::string, std::string>` should likely be an `std::vector<std::pair<std::string, std::string>>`.

**Comment by dkorolev** [comment]
Yes, or `map<std::string, std::vector<string>>`. Thanks!

**Comment by sompylasar** [comment]
refs #99 #100

**Comment by dkorolev** [comment]
Responsed in another issue: We've fixed this for cookies, and the rest hasn't hurt us yet, so closing.
