### ISSUE TITLE
net/http: HTTPDefaultHelper should unify the header names before collecting them

### ISSUE THREAD

**Issue by sompylasar** [C5T/Current#99]
https://github.com/KnowSheet/Bricks/blob/master/net/http/impl/server.h#L84

For example, Express.js does this by lower-casing them.

**Comment by dkorolev** [comment]
@sompylasar : Why don't you do it right on JS side and I'll do it the right way mimicking your logic? :)

**Comment by sompylasar** [comment]
Moreover, `TemplatedHTTPRequestData` should compare header names the case-insensitive way (`stricmp`).

https://github.com/KnowSheet/Bricks/blob/master/net/http/impl/server.h#L222
https://github.com/KnowSheet/Bricks/blob/master/net/http/impl/server.h#L224

**Comment by sompylasar** [comment]
@dkorolev Clever you! :) Sure, I'll do after I've completed with the exact rewrite.

**Comment by dkorolev** [comment]
You're smiling as if it surprises you :)

**Comment by sompylasar** [comment]
@dkorolev Well, I smile because I wanted someone to resolve these issues, not me :)

**Comment by dkorolev** [comment]
Pick your battles :)

Вообще, я, конечно, сделаю эту штуку, она несложная. Только после трёх с половиной релизов (Bricks, FNCAS, Sherlock, Demo).

**Comment by sompylasar** [comment]
На самом деле я создал тикет просто чтобы не забыть.

**Comment by sompylasar** [comment]
refs #98, #100

**Comment by dkorolev** [comment]
This one is actually done -- we keep the original header name, but match by any of its possible spellings, including uppercase vs. lowercase and the interchangability of `'-'` and `'_'`.
